/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TCondicionalSenao extends Token
{
    public TCondicionalSenao()
    {
        super.setText("senao");
    }

    public TCondicionalSenao(int line, int pos)
    {
        super.setText("senao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCondicionalSenao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCondicionalSenao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCondicionalSenao text.");
    }
}
