/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TDecFuncao extends Token
{
    public TDecFuncao()
    {
        super.setText("funcao:");
    }

    public TDecFuncao(int line, int pos)
    {
        super.setText("funcao:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecFuncao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecFuncao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecFuncao text.");
    }
}
