/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TDecFamPassa extends Token
{
    public TDecFamPassa()
    {
        super.setText("passa");
    }

    public TDecFamPassa(int line, int pos)
    {
        super.setText("passa");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecFamPassa(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecFamPassa(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecFamPassa text.");
    }
}
