/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TDecConst extends Token
{
    public TDecConst()
    {
        super.setText("constante:");
    }

    public TDecConst(int line, int pos)
    {
        super.setText("constante:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecConst(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecConst(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecConst text.");
    }
}
