/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TDecObjeto extends Token
{
    public TDecObjeto()
    {
        super.setText("objeto:");
    }

    public TDecObjeto(int line, int pos)
    {
        super.setText("objeto:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecObjeto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecObjeto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecObjeto text.");
    }
}
