/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TDecMolde extends Token
{
    public TDecMolde()
    {
        super.setText("molde");
    }

    public TDecMolde(int line, int pos)
    {
        super.setText("molde");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecMolde(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecMolde(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecMolde text.");
    }
}
