/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TDecFamPor extends Token
{
    public TDecFamPor()
    {
        super.setText("por");
    }

    public TDecFamPor(int line, int pos)
    {
        super.setText("por");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecFamPor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecFamPor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecFamPor text.");
    }
}
