/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TDelimTexto extends Token
{
    public TDelimTexto()
    {
        super.setText("\"");
    }

    public TDelimTexto(int line, int pos)
    {
        super.setText("\"");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDelimTexto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDelimTexto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDelimTexto text.");
    }
}
