/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TEntradaPrograma extends Token
{
    public TEntradaPrograma()
    {
        super.setText(">>");
    }

    public TEntradaPrograma(int line, int pos)
    {
        super.setText(">>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEntradaPrograma(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEntradaPrograma(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEntradaPrograma text.");
    }
}
