/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TFimComando extends Token
{
    public TFimComando()
    {
        super.setText(";");
    }

    public TFimComando(int line, int pos)
    {
        super.setText(";");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimComando(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimComando(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimComando text.");
    }
}
