/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TFimDecMolde extends Token
{
    public TFimDecMolde()
    {
        super.setText("fim");
    }

    public TFimDecMolde(int line, int pos)
    {
        super.setText("fim");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimDecMolde(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimDecMolde(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimDecMolde text.");
    }
}
