/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.node;

import btv.analysis.*;

@SuppressWarnings("nls")
public final class TMoldeContem extends Token
{
    public TMoldeContem()
    {
        super.setText("contem");
    }

    public TMoldeContem(int line, int pos)
    {
        super.setText("contem");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMoldeContem(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMoldeContem(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMoldeContem text.");
    }
}
