/* This file was generated by SableCC (http://www.sablecc.org/). */

package btv.analysis;

import btv.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseTAbrirComentario(TAbrirComentario node);
    void caseTFecharComentario(TFecharComentario node);
    void caseTSe(TSe node);
    void caseTCondicionalEntao(TCondicionalEntao node);
    void caseTCondicionalSenao(TCondicionalSenao node);
    void caseTDecFamPassa(TDecFamPassa node);
    void caseTDecFamPor(TDecFamPor node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTIgualdade(TIgualdade node);
    void caseTMenor(TMenor node);
    void caseTMenorIgual(TMenorIgual node);
    void caseTPonto(TPonto node);
    void caseTSeparadorArg(TSeparadorArg node);
    void caseTE(TE node);
    void caseTOu(TOu node);
    void caseTNeg(TNeg node);
    void caseTEntradaPrograma(TEntradaPrograma node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTAbrirBloco(TAbrirBloco node);
    void caseTFecharBloco(TFecharBloco node);
    void caseTDecMolde(TDecMolde node);
    void caseTMoldeContem(TMoldeContem node);
    void caseTFimDecMolde(TFimDecMolde node);
    void caseTDecConst(TDecConst node);
    void caseTDecObjeto(TDecObjeto node);
    void caseTDecFuncao(TDecFuncao node);
    void caseTFimComando(TFimComando node);
    void caseTTipoPrimitivo(TTipoPrimitivo node);
    void caseTBool(TBool node);
    void caseTTexto(TTexto node);
    void caseTDelimTexto(TDelimTexto node);
    void caseTVazio(TVazio node);
    void caseTIdMolde(TIdMolde node);
    void caseTId(TId node);
    void caseTNumero(TNumero node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
